#test
name: Check File Type

on:
  push:
    branches:
      - main # Or whatever branch you want to trigger on

jobs:
  check_file_type:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file type
        run: |
          for file in $(git ls-files); do
            if [[ -f "$file" ]]; then
              file_type=$(file --mime-type "$file")
              if [[ "$file_type" == *text/plain* ]]; then
                echo "File '$file' is a text file."
              else
                echo "File '$file' is not a text file. It is: $file_type"
              fi
            fi
          done
