name: Hello World

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
