name: Check File Type

on:
  push:
    branches:
      - main

jobs:
  check_file_type:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file type
        run: |
          for file in $(git ls-files); do
            if [[ -f "$file" ]]; then
              if [[ "$file" == *.py ]]; then
                echo "File '$file' is a Python script."
              elif [[ "$(file --mime-type "$file")" == *text/plain* ]]; then
                echo "File '$file' is a plain text file."
              else
                echo "File '$file' is not a text file. It is: $(file --mime-type "$file")"
              fi
            fi
          done
