name: Copy Repository to temp

on:
  push:
    branches:
      - master # Trigger on commits to the master branch

jobs:
  copy_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temp directory
        run: mkdir -p temp

      - name: Copy repository to temp
        run: |
          cp -r . temp/ # Copy all files and directories recursively
          # Optionally remove .git directory within the copy
          # rm -rf temp/.git

      - name: Optional: List files in temp
        run: ls -al temp/ # For debugging purposes
