name: Copy Repository to tmp

on:
  push:
    branches:
      - main

jobs:
  copy_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tmp directory
        run: mkdir -p tmp

      - name: Copy repository to tmp
        run: |
          cp -r . tmp/ # Copy all files and directories recursively
          # Optionally, exclude the .git directory if you don't need it in the copy.
          # rm -rf tmp/.git

      - name: Optional: List files in tmp
        run: ls -al tmp/ # For debugging purposes
