name: Docker Deploy

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker image
      #   id: docker_build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     # Use a specific tag, using github sha to keep versions.
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubaction-demo:${{ github.sha }}
      #     # if you need the latest tag use this line instead of the github sha line above.
      #     # tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
      #     # add this line for multi-platform builds
      #     # platforms: linux/amd64,linux/arm64

      # - name: Echo Image URL
      #   run: echo "Docker Image URL: ${{ steps.docker_build.outputs.digest }}"

      # - name: Check docker login
      #   run: docker info
